# Uncomment the next line to define a global platform for your project
# platform :ios, '14.4'

target 'ECGv1' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ECGv1
  pod 'Charts'

  target 'ECGv1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ECGv1UITests' do
    # Pods for testing
  end

end
